server.address=127.0.0.1
spring.application.name=Khazariasha
spring.datasource.url=jdbc:postgresql://localhost:5432/catering

spring.datasource.username=postgres
spring.datasource.password=xxx
spring.datasource.driver-class-name=org.postgresql.Driver

spring.file_dir=xxx
logging.level.org.springframework.security=DEBUG


spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB
spring.web.resources.cache.period=0

spring.mvc.pathmatch.matching-strategy=ant_path_matcher

